### ISSUE TITLE
CSS Classes

### ISSUE THREAD

**Issue by zachfedor** [DomBouman/more-css-practice#2]
https://github.com/DomBouman/more-css-practice/blob/3c00897f16dc01ca1bb0b6ccd60493ede9851b95/airbnb/styles.css#L70-L93

Dom, the point of CSS Classes is so you can create groups of like elements and style them all with one ruleset. Instead of copying and pasting your class over and over, just make one!
```css
 .bottom { 
   width: 33%; 
   float: left; 
   border: solid .5px; 
   display: inline-block; 
   padding-top: 3px; 
   padding-left: 3px; 
 }
```
Then give all three of those elements the same class   😄 
```html
<section class="bottom">
  <a href="https://placeholder.com"><img src="https://via.placeholder.com/100x100"></a>
  <p class="center"> Homes </p>
</section>
<section class="bottom">
  <a href="https://placeholder.com"><img src="https://via.placeholder.com/100x100"></a>
  <p class="center"> Experiences </p>
</section>
<section class="bottom">
  <a href="https://placeholder.com"><img src="https://via.placeholder.com/100x100"></a>
  <p class="center"> Restaurants </p>
</section>
```

Now all three look the same, and if you need to make a change, you only have to do it once for all of them!
